### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [bentonelli/MIMAS#1]
to clarify reusability (same issue on Zenodo).

**Comment by bentonelli** [comment]
Added license to both Zenodo and Github

**Comment by Daniel-Mietchen** [comment]
@bentonelli Thanks for the quick reaction. However, you chose AGPL3 here and GPL3 on Zenodo. Can you take another look and harmonize that?

**Comment by bentonelli** [comment]
rectified now
